### ISSUE TITLE
Auto-hash binary or directory via command-line and associate with key

### ISSUE THREAD

**Issue by t-lin** [Multi-Tier-Cloud/hash-lookup#1]
(todo)

**Comment by t-lin** [comment]
Works for single file right now.
Directory currently cats file contents and then takes hash, this part needs to be re-designed (e.g. look into what ipfs does).

**Comment by hivanco** [comment]
Uses same methods as ipfs for creating merkle dag from given file or directory, and takes hash from root node.
https://github.com/Multi-Tier-Cloud/hash-lookup/commit/c6a38a2919a519bacaa48b191b04203b588fae4a
